lab:
  network: 10.10.0.0/24
  nodes:
    broker:
      build: custom_broker
      replicas: 2
    client0:
      image: nicolaka/netshoot
      script: /bin/bash script0.sh
      ip: 10.10.0.1
      needs:
        - broker
    client1:
      image: nicolaka/netshoot
      script: /bin/bash script1.sh
      ip: 10.10.0.2
      replicas: 1
      needs:
        - broker
