lab:
  network: 10.10.0.0/24
  nodes:
    broker:
      build: custom_broker
    client0:
      image: nicolaka/netshoot
      script: /bin/bash script0.sh
      needs:
        - broker
    client1:
      image: nicolaka/netshoot
      script: /bin/bash script1.sh
      needs:
        - broker
