name: lab
networks:
  lab_network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.0.0/24
      driver: default
services:
  broker:
    build: custom_broker
    networks:
      lab_network:
        ipv4_address: 10.10.0.2
    volumes:
    - ./:/workspace
  client211_0:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script0.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.16
    volumes:
    - ./:/workspace
  client211_1:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script0.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.17
    volumes:
    - ./:/workspace
  client22_0:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script0.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.3
    volumes:
    - ./:/workspace
  client22_1:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script0.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.4
    volumes:
    - ./:/workspace
  client312:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script1.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.8
    volumes:
    - ./:/workspace
  client312_bis:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script1.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.5
    volumes:
    - ./:/workspace
  client4:
    depends_on:
    - broker
    entrypoint: /bin/bash /workspace/script1.sh
    image: nicolaka/netshoot
    networks:
      lab_network:
        ipv4_address: 10.10.0.6
    volumes:
    - ./:/workspace
version: 1.0.0
